// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  biography: dynamic(() => import("./Biography")),
  contact: dynamic(() => import("./Contact")),
  education: dynamic(() => import("./Education")),
  experience: dynamic(() => import("./Experience")),
  hero: dynamic(() => import("./Hero")),
  projects: dynamic(() => import("./Projects")),
  tech_list: dynamic(() => import("./TechList")),
  testimonials: dynamic(() => import("./Testimonials")),
  text_block: dynamic(() => import("./TextBlock")),
};
